package hammerspoon;

@:native("hs.httpserver")
extern class HttpServer {
  @:native("new") @:luaDotMethod static public function make(ssl:Bool, bonjour:Bool):HttpServer;
  public function getInterface():Null< String >;
  public function getName():String;
  public function getPort():Int;
  public function maxBodySize(size:Int):Dynamic;
  public function send(message:String):Void;
  public function setCallback(callback:Dynamic):Void;
  public function setInterface(interfaceName:String):Void;
  public function setName(name:String):Void;
  public function setPassword(password:String):Void;
  public function setPort(port:Int):Void;
  public function start():Void;
  public function stop():Void;
  public function websocket(path:String, callback:Dynamic):Void;
}

@:native("hs.alert")
extern class Alert {
  /**
   * Closes all alerts currently open on the screen
   * @param seconds Optional number specifying the fade out duration. Defaults to `fadeOutDuration` value currently defined in the [hs.alert.defaultStyle](#defaultStyle)
   * @return None
   */
  @:luaDotMethod static public function closeAll(seconds:Null< Float >):Void;

  /**
   * Closes the alert with the specified identifier
   * @param uuid    the identifier of the alert to close
   * @param seconds Optional number specifying the fade out duration. Defaults to `fadeOutDuration` value currently defined in the [hs.alert.defaultStyle](#defaultStyle)
   * @return None
   * @notes Use this function to close an alert which is indefinite or close an alert with a long duration early.
   */
  @:luaDotMethod static public function closeSpecific(uuid:String, seconds:Null< Float >):Void;

  /**
   * A table defining the default visual style for the alerts generated by this module.
   */
  static public var defaultStyle:Dynamic;

  /**
   * Shows a message in large words briefly in the middle of the screen; does tostring() on its argument for convenience.
   * @param str The string or `hs.styledtext` object to display in the alert
   * @param style an optional table containing one or more of the keys specified in [hs.alert.defaultStyle](#defaultStyle). If `str` is already an `hs.styledtext` object, this argument is ignored.
   * @param screen an optional `hs.screen` userdata object specifying the screen (monitor) to display the alert on. Defaults to `hs.screen.mainScreen()` which corresponds to the screen with the currently focused window.
   * @param seconds The number of seconds to display the alert. Defaults to 2. If seconds is specified and is not a number, displays the alert indefinitely.
   * @return a string identifier for the alert.
   * @notes For convenience, you can call this function as `hs.alert(...)`
   */
  @:luaDotMethod static public function show(str:Dynamic, ?style:Dynamic, ?screen:Dynamic, ?seconds:Null< Float >):String;

  /**
   * Shows an image and a message in large words briefly in the middle of the screen; does tostring() on its argument for convenience.
   * @param str The string or `hs.styledtext` object to display in the alert
   * @param image The image to display in the alert
   * @param style an optional table containing one or more of the keys specified in [hs.alert.defaultStyle](#defaultStyle). If `str` is already an `hs.styledtext` object, this argument is ignored.
   * @param screen an optional `hs.screen` userdata object specifying the screen (monitor) to display the alert on. Defaults to `hs.screen.mainScreen()` which corresponds to the screen with the currently focused window.
   * @param seconds The number of seconds to display the alert. Defaults to 2. If seconds is specified and is not a number, displays the alert indefinitely.
   * @return a string identifier for the alert.
   * @notes The optional parameters are parsed in the order presented as follows:
   *        if the argument is a table and `style` has not previously been set, then the table is assigned to `style`
   *        if the argument is a userdata and `screen` has not previously been set, then the userdata is assigned to screen
   * if duration has not been set, then it is assigned the value of the argument
   * if all of these conditions fail for a given argument, then an error is returned
   * The reason for this logic is to support the creation of persistent alerts as was previously handled by the module: If you specify a non-number value for seconds you will need to store the string identifier returned by this function so that you can close it manually with hs.alert.closeSpecific when the alert should be removed.
   * Any style element which is not specified in the style argument table will use the value currently defined in the hs.alert.defaultStyle table.
   */
  @:luaDotMethod static public function showWithImage(
    str:Dynamic,
    image:Dynamic,
    ?style:Dynamic,
    ?screen:Dynamic,
    ?seconds:Null< Float >
  ):String;
}

@:native("hs.json")
extern class Json {
  /**
   * Decodes JSON into a table
   *
   * Parameters:
   *  * jsonString - A string containing some JSON data
   *
   * Returns:
   *  * A table representing the supplied JSON data
   *
   * Notes:
   *  * This is useful for retrieving some of the more complex lua table structures as a persistent setting (see `hs.settings`)
   */
  @:luaDotMethod static public function decode(jsonString:String):Dynamic;

  /**
   * Encodes a table as JSON
   *
   * Parameters:
   *  * val         - A table containing data to be encoded as JSON
   *  * prettyprint - An optional boolean, true to format the JSON for human readability, false to format the JSON for size efficiency. Defaults to false
   *
   * Returns:
   *  * A string containing a JSON representation of the supplied table
   *
   * Notes:
   *  * This is useful for storing some of the more complex lua table structures as a persistent setting (see `hs.settings`)
   */
  @:luaDotMethod static public function encode(val:Dynamic, ?prettyprint:Bool):String;

  /**
   * Decodes JSON file into a table.
   *
   * Parameters:
   *  * path - The path and filename of the JSON file to read.
   *
   * Returns:
   *  * A table representing the supplied JSON data, or `nil` if an error occurs.
   */
  @:luaDotMethod static public function read(path:String):Dynamic;

  /**
   * Encodes a table as JSON to a file
   *
   * Parameters:
   *  * data       - A table containing data to be encoded as JSON
   *  * path       - The path and filename of the JSON file to write to
   *  * prettyprint - An optional boolean, `true` to format the JSON for human readability, `false` to format the JSON for size efficiency. Defaults to `false`
   *  * replace     - An optional boolean, `true` to replace an existing file at the same path if one exists. Defaults to `false`
   *
   * Returns:
   *  * `true` if successful otherwise `false` if an error has occurred
   */
  @:luaDotMethod static public function write(data:Dynamic, path:String, ?prettyprint:Bool, ?replace:Bool):Bool;
}

@:native("hs.logger")
extern class Logger {
  /**
   * Logs debug info to the console
   *
   * Parameters:
   *  * ... - one or more message strings
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function d(...params:String):Void;

  /**
   * Default log level for new logger instances.
   *
   * The starting value is 'warning'; set this (to e.g. 'info') at the top of your `init.lua` to affect
   * all logger instances created without specifying a `loglevel` parameter
   */
  static public var defaultLogLevel(default, null):Int;

  /**
   * Logs formatted debug info to the console
   *
   * Parameters:
   *  * fmt - formatting string as per string.format
   *  * ... - arguments to fmt
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function df(fmt:String, ...params:String):Void;

  /**
   * Logs an error to the console
   *
   * Parameters:
   *  * ... - one or more message strings
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function e(...params:String):Void;

  /**
   * Logs a formatted error to the console
   *
   * Parameters:
   *  * fmt - formatting string as per string.format
   *  * ... - arguments to fmt
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function ef(fmt:String, ...params:String):Void;

  /**
   * Logs formatted info to the console
   *
   * Parameters:
   *  * fmt - formatting string as per string.format
   *  * ... - arguments to fmt
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function f(fmt:String, ...params:String):Void;

  /**
   * Gets the log level of the logger instance
   *
   * Parameters:
   *  * None
   *
   * Returns:
   *  * The log level of this logger as a number between 0 and 5
   */
  @:luaDotMethod static public function getLogLevel():Int;

  /**
   * Returns the global log history
   *
   * Parameters:
   *  * None
   *
   * Returns:
   *  * a list of (at most `hs.logger.historySize()`) log entries produced by all the logger instances, in chronological order;
   *    each entry is a table with the following fields:
   *    * time - timestamp in seconds since the epoch
   *    * level - a number between 1 (error) and 5 (verbose)
   *    * id - a string containing the id of the logger instance that produced this entry
   *    * message - a string containing the logged message
   */
  @:luaDotMethod static public function history():Array< Dynamic >;

  /**
   * Sets or gets the global log history size
   *
   * Parameters:
   *  * size - (optional) the desired number of log entries to keep in the history;
   *    if omitted, will return the current size; the starting value is 0 (disabled)
   *
   * Returns:
   *  * the current or new history size
   *
   * Notes:
   *  * if you change history size (
   * other than from 0) after creating any logger instances, things will likely break
   */
  @:luaDotMethod static public function historySize(size:Int = -1):Int;

  /**
   * Logs info to the console
   *
   * Parameters:
   *  * ... - one or more message strings
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function i(...params:String):Void;

  /**
   * The log level of the logger instance, as a number between 0 and 5
   */
  public var level(default, null):Int;

  /**
   * Creates a new logger instance
   *
   * Parameters:
   *  * id - a string identifier for the instance (usually the module name)
   *  * loglevel - (optional) can be 'nothing', 'error', 'warning', 'info', 'debug', or 'verbose', or a corresponding number
   *    between 0 and 5; uses `hs.logger.defaultLogLevel` if omitted
   *
   * Returns:
   *  * the new logger instance
   */
  @:luaDotMethod static public function new(id:String, loglevel:Int = -1):Logger;

  /**
   * Prints the global log history to the console
   *
   * Parameters:
   *  * entries - (optional) the maximum number of entries to print; if omitted, all entries in the history will be printed
   *  * level - (optional) the desired log level (see `hs.logger.setLogLevel()`); if omitted, defaults to `verbose`
   *  * filter - (optional) a string to filter the entries (by logger id or message) via `string.find` plain matching
   *  * caseSensitive - (optional) if true, filtering is case sensitive
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function printHistory(
    entries:Int = -1,
    level:Int = -1,
    filter:String = "",
    caseSensitive:Bool = false
  ):Void;

  /**
   * Sets the log level for all logger instances (including objects' loggers)
   *
   * Parameters:
   *  * lvl
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function setGlobalLogLevel(lvl:Int):Void;

  /**
   * Sets the log level of the logger instance
   *
   * Parameters:
   *  * loglevel - can be 'nothing', 'error', 'warning', 'info', 'debug', or 'verbose'; or a corresponding number between 0 and 5
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod public function setLogLevel(loglevel:Int):Void;

  /**
   * Sets the log level for all currently loaded modules
   *
   * Parameters:
   *  * lvl
   *
   * Returns:
   *  * None
   *
   * Notes:
   *  * This function only affects *module*-level loggers, object instances with their own loggers (e.g. windowfilters) won't be affected;
   *    you can use `hs.logger.setGlobalLogLevel()` for those
   */
  @:luaDotMethod static public function setModulesLogLevel(lvl:Int):Void;

  /**
   * Logs verbose info to the console
   *
   * Parameters:
   *  * ... - one or more message strings
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function v(...params:String):Void;

  /**
   * Logs formatted verbose info to the console
   *
   * Parameters:
   *  * fmt - formatting string as per string.format
   *  * ... - arguments to fmt
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function vf(fmt:String, ...params:String):Void;

  /**
   * Logs a warning to the console
   *
   * Parameters:
   *  * ... - one or more message strings
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function w(...params:String):Void;

  /**
   * Logs a formatted warning to the console
   *
   * Parameters:
   *  * fmt - formatting string as per string.format
   *  * ... - arguments to fmt
   *
   * Returns:
   *  * None
   */
  @:luaDotMethod static public function wf(fmt:String, ...params:String):Void;
}

