name: Build and Zip StreamDeckButton Spoon

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: simple
        package-name: StreamDeckButton.spoon
        extra-files: init.lua

    - name: Zip Spoon
      if: ${{ steps.release.outputs.release_created }}
      run: |
        if [ -f StreamDeckButton.spoon.zip ]; then
          rm StreamDeckButton.spoon.zip
        fi
        zip -r StreamDeckButton.spoon.zip . -x '*.git*' -x '*.github*'

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: ${{ steps.release.outputs.release_created }}
      with:
        name: StreamDeckButton.spoon
        path: StreamDeckButton.spoon.zip
    - name: Upload Release Asset
      if: ${{ steps.release.outputs.release_created }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ steps.release.outputs.tag_name }}
      run: |
        gh release upload $TAG_NAME StreamDeckButton.spoon.zip
