name: Build and Zip StreamDeckButton Spoon

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip Spoon
      run: |
        if [ -f StreamDeckButton.spoon.zip ]; then
          rm StreamDeckButton.spoon.zip
        fi
        zip -r StreamDeckButton.spoon.zip . -x '*.git*' -x '*.github*'

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: StreamDeckButton.spoon.zip
        path: StreamDeckButton.spoon.zip
